services:
  accounts:
    image: bachdx202156/accounts-service:v1.0
    container_name: accounts_service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - bank
  loans:
    image: bachdx202156/loans-service:v1.0
    container_name: loans_service
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - bank
  cards:
    image: bachdx202156/cards-service:v1.0
    container_name: cards_service
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - bank
networks:
    bank:
      driver: bridge
